### ISSUE TITLE
Claiming of using Rust while having no Rust code

### ISSUE THREAD

**Issue by tripulse** [AVCADO/SSFTP#8]
The `README.md` contains a section "Technologies Used" in which it describes that it uses Rust language as primarily for the source code and [`openssl`](https://crates.io/crates/openssl), [`ftp`](https://crates.io/crates/ftp) crates for making it possible.

![image](https://user-images.githubusercontent.com/37257726/84493930-3fac9b00-acc6-11ea-910c-2911f65b6682.png)

But as of Github I get these statistics:
![image](https://user-images.githubusercontent.com/37257726/84495368-afbc2080-acc8-11ea-9a48-1d795c4ab8dc.png)

**Comment by AVCADO** [comment]
I am aware of this. I have not changed this yet. I will change it now.
